### ISSUE TITLE
Categories/Collections/Types for accessories

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#1]
We know for sure there are Napkins, Placemats, and Aprons.
Do these each get treated as a "category" or a "collection"?
Whatever solution should account for the fact that they might add additional "collections" or "types" in the future...

**Comment by webmasterkai** [comment]
Do/should we create products before we have images?

**Comment by bjornmeansbear** [comment]
This is broken into smaller constiuent questions/issues now.
