### ISSUE TITLE
Tags: How to utilize this best?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#14]
On DL and RG there is some tagging that happens already; do we just replicate those same kinds of tags for the products on the webstore to create the setup for similar kinds of searching/filtering?

**Comment by bjornmeansbear** [comment]
Can we get things like the color tags from order track to become tags in shopify that can be assigned to the accessories? is there then a way to automate this accessory item getting these tags since it shares pattern and color #s with a textile?

**Comment by webmasterkai** [comment]
Looks like they added some items with tags. They show up in the dropdown on the https://summersalefinetextiles.com/collections/all page

**Comment by bjornmeansbear** [comment]
They'll be using tags for colors, manual entry.
