### ISSUE TITLE
Sample Images for Napkins and Placemats

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#2]
They sent me a handful of sample images; its not what they're thinking probably for the final stages; but its at least some other kinds of imagery to try and use. What's the best way to proceed? do we need images for each thing to create them? can images be easily added after the fact? can we use a couple images universally and then have them swap images themselves as they get them taken?

**Comment by webmasterkai** [comment]
* Should we just have them upload images directly to Shopify via the interface there?
* We can create products without images. Works best if each variation has its own image but if that isn't happening we can think about how to group multiple product options within one "example" image.
*  Images be easily added at any time via the interface if that's the way we decide.
* We can have a custom default image

**Comment by bjornmeansbear** [comment]
Moving forward we'll try to get them to take/upload images themselves where possible.
