### ISSUE TITLE
Different types of accessories are collections

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#20]

**Comment by webmasterkai** [comment]
These can be automatic collections that are created based on some keyword in the title like "napkin" or a `tag` value that's assigned to the product.

**Comment by bjornmeansbear** [comment]
Can they automatically group into the right collection based on the suffix of their sku?
```
For Napkins = NP
For Aprons = AP
For Bag = BG
For Bread Baskets = BB
For Placemats = PM
```
