### ISSUE TITLE
Should we just have them upload images directly to Shopify via the interface there?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#3]
It probably makes sense to ask them to upload images themselves as new accessories in new colorways show up? I don't think they'll be sending these to a photographer as they have few in quantity, and that the fabrics are all discontinued, so there is limited stock and its not worth having a nice image that will be reused for years to come... ?

Short answer: Yes.

So I need to get them setup w/ the shopify apps?

**Comment by webmasterkai** [comment]
Do we want to have products created first? Is there a list of example products somewhere?

**Comment by bjornmeansbear** [comment]
They told me napkins, etc. are in order track... do they show up in RG or DL's data anywhere? I haven't had occasion to look... that might be another great set of conversations with PDF systems

**Comment by webmasterkai** [comment]
There are some things in there but they don’t have any useful meta data. I mentioned it on slack previously I think. I’ll try to find it

**Comment by bjornmeansbear** [comment]
duh. the links to the data are right in the readme

**Comment by bjornmeansbear** [comment]
They want to use Shopify as the inventory tool for accessories; so I'll be trying to get them up to speed on how to do that as we figure out some of the other things.
