### ISSUE TITLE
Product type: There is Textile & Textiles / just make it textile?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#34]
Can we simplify this and just have one option; the singular `textile` ??

**Comment by webmasterkai** [comment]
It's a direct copy of the order track `category` field. The other product types are plural. Are you going to change `aprons` and `napkins` to singular form too?

**Comment by webmasterkai** [comment]
I'm going to go with singular uppercase for now.

**Comment by bjornmeansbear** [comment]
IS this resolved? all versions of TEXTILE, TEXTILES, Textile, etc. are now Textile?

**Comment by bjornmeansbear** [comment]
looks resolved?
