### ISSUE TITLE
Textiles/Passementerie should only be purchaseable in the physical store

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#37]
But! they still need to be in Shopify, and show up, just not purchasable online -- only purchasable in the store.

**Comment by webmasterkai** [comment]
This will probably be something custom. It could be done with inventory control. Just say the inventory is 0 and Shopify will display but prevent users from being able to purchase. But then they can't use inventory tracking for what they have available in the store. Will have to look into this more.

**Comment by bjornmeansbear** [comment]
that's not useful. Shoot, since they want to be able to sell stuff in store, its convenient to have all the quantity info onboard...

though perhaps its okay to talk to them about? 

We should just have it not show as a first iteration I guess. Then we can broach the subject with them more esaily?

**Comment by bjornmeansbear** [comment]
1. Textile Yardages should not be buyable online, only at store.
2. Textile Yardages should be viewable online still

Is this an issue of being able to divide the inventory across "locations" -- POS being one location; online store another? https://help.shopify.com/en/manual/locations/assigning-inventory-to-locations

**Comment by bjornmeansbear** [comment]
Also, I actually clicked through the POS stuff, so its officially "on" maybe that changes where inventory can live?

**Comment by bjornmeansbear** [comment]
okay, well, just making an item available at POS and unchecking the ONline Store option does remove it completely from the online store. A step in learning what not to do; but this is not desirable.

**Comment by bjornmeansbear** [comment]
Aha, getting closer
https://help.shopify.com/en/manual/locations/assigning-inventory-to-locations
> Optional: In the bulk editor, click Add fields and add fields for the locations where you want to stock the products.
> In the cells of the bulk editor, check or uncheck Stock at this location. You can also update the quantities, such as in this example:

**Comment by bjornmeansbear** [comment]
@webmasterkai Hey, do you think we can do something to how the items get brought in? like the inventory automatically gets assigned to the POS, and Online store is another location with no stock???

**Comment by bjornmeansbear** [comment]
f, that appears to just be for multiple physical store locations...

**Comment by bjornmeansbear** [comment]
mother f-er, one option is to duplicate the items... https://community.shopify.com/c/Shopify-POS/Different-Price-for-POS-and-Online/m-p/442321

**Comment by bjornmeansbear** [comment]
Aha, there is something important about what is the "shipping origin"
https://help.shopify.com/en/manual/locations

So, maybe if we have a 41 chestnut "Yardage" location and a 41 chestnut regular ??? hmmm some way to have those things show up only then as inventory on the no online sales one; maybe they'd then show up even if inventory for online sales is 0???

**Comment by bjornmeansbear** [comment]
https://summersalefinetextiles.com/products/91024-08

Okay, this one shows up but inventory is 0 for online; POS would be able to see it? does having multiple locations then F up how the POS system will work!?

**Comment by bjornmeansbear** [comment]
Need to automate changin layouts now, but solved!
