### ISSUE TITLE
Make a "homepage" collection to draw images from for textile slivers

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#44]
https://codepen.io/bjornmeansbear/pen/vYBMeej

Is the homepage list of textiles updateable? It would be easy enough to make a special Shopify collection just called homepage or similar, you could then add and remove things manually that way. Otherwise we could randomly pick 50 items each time so it’s always a little bit different.

**Comment by bjornmeansbear** [comment]
made the collection. check. https://summersalefinetextiles.com/collections/frontpage

**Comment by webmasterkai** [comment]
The [homepage](https://summer-sale-fine-textiles.myshopify.com/admin/pages/47037481048) is two rows that display fabric textiles available by the yard. The rows are generated from the Shopify [Home Page](https://summer-sale-fine-textiles.myshopify.com/admin/collections/91431632984) collection. 

We have a cloudflare worker that does the following:

1. Trigger by visiting https://summersale.ookb.workers.dev/
1. Request collection, get first 46 products and first SKU of each.
2. Request imgix color information for every product.
3. Add color HSL information for the color.
4. Sort by some attribute.
5. Split the items in half to make `top` and `bottom`.
6. Send it to a template (javascript literal) that creates html text.
7. Load previously saved [template from shopify](https://summer-sale-fine-textiles.myshopify.com/admin/themes/37580275800?key=templates/page.landingpage.liquid).
8. Compare old vs new generated template.
9. Save if html changes found.
10. Return result to browser.
