### ISSUE TITLE
What do I need to ask/talk to RG/DL about re: getting more items

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#5]
Are there better ways we need the items entered? -- napkins, placemats, etc. are pretty useless in the current data structure -- just entered as "Apron" or "Bag" or "Napkin set of 6"

How do we help them make this better; and make our job easier!?

**Comment by webmasterkai** [comment]
Using Shopify instead of trying to get order track to do something useful is going to be 1000 times easier.

**Comment by bjornmeansbear** [comment]
check. They will be entering things into shopify and using it to track inventory.
