### ISSUE TITLE
register domain for them...

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/summersale#7]
Esteban sent requested domain in an email, find it and register it for them!

**Comment by bjornmeansbear** [comment]
http://www.sumersalefinetextiles.com/

**Comment by webmasterkai** [comment]
Looks like new domain registration was turned off at Cloudflare? I don't see it anymore. Only transfers. :-(

**Comment by bjornmeansbear** [comment]
Okay cool, I'll just get it on enom and send er over

±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

Kristian Bjørnard
Designer / Thinker / Sustainabilitist

ph:  507.301.8402
em: kb@ookb.co
w:   www.ookb.co
w:   www.cape.io
twitter: @bjornmeansbear

**Comment by bjornmeansbear** [comment]
f me. typo, now I have sumersale and summersale... stupid not checking before I hit "buy"

**Comment by webmasterkai** [comment]
Sounds like a feature
